// ---------------------------------------------------------
// 1. COURSE DATA
// Edit this array with your real courses. `completed: true`
// means you have already taken/finished that course.
// ---------------------------------------------------------
const courses = [
  { subject: "WDD", number: 130, credits: 2, completed: true },
  { subject: "WDD", number: 131, credits: 2, completed: true },
  { subject: "WDD", number: 231, credits: 2, completed: false },
  { subject: "CSE", number: 111, credits: 2, completed: true },
  { subject: "CSE", number: 210, credits: 3, completed: false },
];

const courseListEl = document.getElementById("courseList");
const totalCreditsEl = document.getElementById("totalCredits");
const filterButtons = document.querySelectorAll(".buttons button");

// ---------------------------------------------------------
// 2. RENDER COURSES (criterion 8: dynamic display from array)
// ---------------------------------------------------------
function renderCourses(courseArray) {
  courseListEl.innerHTML = ""; // clear previous render

  courseArray.forEach((course) => {
    const card = document.createElement("div");
    card.classList.add("course");
    if (course.completed) {
      card.classList.add("completed"); // criterion 11: mark completed courses
    }

    card.innerHTML = `
      <span class="course-name">${course.subject} ${course.number}</span>
      <span class="course-credits">${course.credits} cr</span>
      ${course.completed ? '<span class="badge">✓ Completed</span>' : ""}
    `;

    courseListEl.appendChild(card);
  });

  updateTotalCredits(courseArray);
}

// ---------------------------------------------------------
// 3. TOTAL CREDITS using reduce() (criterion 10)
// ---------------------------------------------------------
function updateTotalCredits(courseArray) {
  const total = courseArray.reduce((sum, course) => sum + course.credits, 0);
  totalCreditsEl.textContent = total;
}

// ---------------------------------------------------------
// 4. FILTER BUTTONS (criterion 9: dynamic filter)
// ---------------------------------------------------------
filterButtons.forEach((button) => {
  button.addEventListener("click", () => {
    // toggle active styling on the buttons themselves
    filterButtons.forEach((btn) => btn.classList.remove("active"));
    button.classList.add("active");

    const filter = button.dataset.filter;
    const filtered =
      filter === "all"
        ? courses
        : courses.filter((course) => course.subject === filter);

    renderCourses(filtered);
  });
});

// Initial render on page load
renderCourses(courses);

// ---------------------------------------------------------
// 5. FOOTER: copyright year + last modified (criterion 12)
// Generated by JS, not hard-coded.
// ---------------------------------------------------------
document.getElementById("currentYear").textContent = new Date().getFullYear();
document.getElementById("lastModified").textContent = document.lastModified;